spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3312/mybatis-plus?characterEncoding=UTF-8
#    username: root
#    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: zc
    password: 123456
    mapperLocations: classpath*:mapper/**/*.xml


logging:
  level:
    root: info
    com.zc.mybatisplus.dao: debug





